### ISSUE TITLE
Succesful log in attempts

### ISSUE THREAD

**Issue by kiankris** [kiankris/Globitek#19]
set the failed logins count to 0

**Comment by codepathreview** [comment]
Hello Kiankris,


:+1: Nice work! User authentication has become a standard feature of almost every modern web application. But knowing how to authenticate is not enough, developers must know the common security pitfalls and how to avoid them.

Key points to remember:
* *Always* encrypt passwords before storing them!
* Require users to choose strong passwords (long, diverse characters).
* Use a secure password algorithm, like Blowfish/Bcrypt.
* Salts are added to passwords to make them unique and harder to crack.
* Log in throttling makes brute force attacks and password guessing ineffective.
* Do not accidentally reveal which usernames exist. (Username enumeration)

If you have any particular questions about the assignment or the feedback, email us at <universitysupport@codepath.com>.

**Comment by codepathreview** [comment]
:+1: Nice work! It is important to recognize and to understand how these six common vulnerabilities function. And of course, you should know how to fix the code once you identify the problem!

If you have any particular questions about the assignment or the feedback, email us at universitysupport@codepath.com.
